version: 0.1

phases:
  pre_build:
    commands:
      - echo Iniciando o processo de build
      - echo `date +%s` > timestamp
      - echo Logando no Docker HUN
      - docker login -u arthurosilva -p pantokrator
  build:
    commands:
      - echo Biuldando o container
      - docker build -t site .
      - echo Criando a tag
      - docker tag site arthurosilva/site:latest
  post_build:
    commands:
      - echo Push da imagem docker no Docker HUB
      - docker push arthurosilva/site:latest
      # echo Preparing CloudFormation Artifacts
      # aws s3 cp s3://$ECS_SERVICE_BUCKET/$ECS_SERVICE_KEY task-definition.template
      # aws s3 cp s3://$ECS_SERVICE_PARAMS_BUCKET/$ECS_SERVICE_PARAMS_KEY cf-config.json
      # We assume the parameters json file has IMAGE_NAME_PLACEHOLDER in it, if not this will not work
      # sed -i "s/IMAGE_NAME_PLACEHOLDER/$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com\/$(cat ./repo_name):$BRANCH-$(cat ./timestamp)/g" ./cf-config.json
      - printf '[{"name":"arn:aws:ecs:sa-east-1:334399188311:cluster/site2","imageUri":"arthurosilva/site:latest"}]' > imagedefinitions.json
